### ISSUE TITLE
Broken url in repository header

### ISSUE THREAD

**Issue by duianto** [bradyt/dart-server#6]
The http://code.google.com/p/dart-mode link at the top of the main page:
>An Emacs minor mode for the Dart server http://code.google.com/p/dart-mode

leads to a 404 page:
>404. That's an error.
The project dart-mode was not found.

**Comment by bradyt** [comment]
Oh, interesting. That link was in title from when dart-mode was transferred to me. I wonder when they broke the link. Okay, I've removed it from the title section, thank you for pointing out.
